### ISSUE TITLE
ERROR: Cannot find the SQL Server container for config: config-demo-backup. Please redeploy before running this task again.

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-containers#3]
I tried to upgrade via option 1, manage-environment -t upgrade'. I was using a postgres database but changed this to sql in the variables.conf. After this change it worked, but I assume that this should also work for Postgres.

BACKUP DATABASE successfully processed 1234 pages in 0.184 seconds (52.373 MB/sec).

#----------------------------------------------------------------------
# Stopping SQL Server container
#----------------------------------------------------------------------
sqlserver.config-demo_4.4.1

#----------------------------------------------------------------------
# Creating backup for: config-demo-backup
#----------------------------------------------------------------------

ERROR: Cannot find the SQL Server container for config: config-demo-backup. Please redeploy before running this task again.

**Comment by Anthony-Johnson-i2** [comment]
Hi Steven

I am not sure of what you are asking here. Had  you re tweaked your config so that it would work again with Postgres and it is still trying to reference SQL server or were you trying something else?

Cheers

**Comment by Kirk-Fitzsimons-i2** [comment]
Hi Steven,

Thank you for raising the issue, can I ask that you please use the "Issue: Bug report" template provided when raising issues, it will help us to evaluate and debug the issue easier.

`**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Run scripts '...'
2. Go to '...'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Hardware and Software information**
Fill in the following information:

- OS: [e.g. Mac, Windows]
- Version: [e.g. v2.0.0]
- i2 Analyze version: [e.g. 4.3.4]
- Environment type: [e.g. pre-prod, config-dev]
- Deployment pattern: [e.g. istore, i2c, cstore, i2c_istore, i2c_cstore, schema_dev]

**Additional context**
Add any other context about the problem here.
`

Can you specify the state of the system before the upgrade (running with postgres/sqlserver) and the commands run after that.

Kirk

**Comment by Kirk-Fitzsimons-i2** [comment]
Here is the template:


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Run scripts '...'
2. Go to '...'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Hardware and Software information**
Fill in the following information:

- OS: [e.g. Mac, Windows]
- Version: [e.g. v2.0.0]
- i2 Analyze version: [e.g. 4.3.4]
- Environment type: [e.g. pre-prod, config-dev]
- Deployment pattern: [e.g. istore, i2c, cstore, i2c_istore, i2c_cstore, schema_dev]

**Additional context**
Add any other context about the problem here.

**Comment by sdorresteijn88** [comment]
Morning Kirk,

I was running the system with Postgres on docker containers. i2 Analyse version 4.4.1 and analyze containers version 2.5.0. I tried to upgrade to the analyze containers version 2.5.2, https://i2group.github.io/analyze-containers/content/managing_upgrade_env.html.

I followed the steps in the prerequisites. But I got the Postgres errors, mentioned in the other ticket. Below the steps:

I removed the other configs (they gave also the Postgres errors)
I changed the db from Postgres to SQL
I used the command 'manage-environment -t upgrade', https://i2group.github.io/analyze-containers/content/managing_upgrade_env.html#option-1.
Choose y for 'This upgrade uses the same version of i2 Analyze. The process will upgrade your environment in /home/sdor/analyze-containers. Do you want to continue? (y/n) y'
Choose y for 'Do you want to override the existing backup? (y/n) y'


See below the whole terminal output
This application is configured for access on https://i2analyze.eia:9443/opal
vscode ➜ /home/sdor/analyze-containers $ manage-environment -t upgrade

This upgrade uses the same version of i2 Analyze. The process will upgrade your environment in /home/sdor/analyze-containers. Do you want to continue? (y/n) y


#----------------------------------------------------------------------
# Stopping containers for other configs
#----------------------------------------------------------------------
sqlserver.config-demo_4.4.1
liberty1.config-demo_4.4.1
grafana.config-demo_4.4.1
prometheus.config-demo_4.4.1
solr1.config-demo_4.4.1
zk1.config-demo_4.4.1

#----------------------------------------------------------------------
# Stopping connector containers for other configs
#----------------------------------------------------------------------
connector-anpr-connector
connector-car-registration-connector
connector-holehe-connector

#----------------------------------------------------------------------
# Creating backup for: config-demo
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# Starting SQL Server container
#----------------------------------------------------------------------
sqlserver.config-demo_4.4.1

#----------------------------------------------------------------------
# Waiting for SQL Server to be live
#----------------------------------------------------------------------
           
-----------
          1

(1 rows affected)
SQL Server is live
There is already a backup for config-demo config with the name global-upgrade.

Do you want to override the existing backup? (y/n) y


#----------------------------------------------------------------------
# Backing up the ISTORE database for container: sqlserver.config-demo_4.4.1
#----------------------------------------------------------------------
Changed database context to 'ISTORE'.
Processed 960 pages for database 'ISTORE', file 'IStore_System_Data' on file 1.
Processed 496 pages for database 'ISTORE', file 'User_Table_Data' on file 1.
Processed 16 pages for database 'ISTORE', file 'IStore_Indexes' on file 1.
Processed 40 pages for database 'ISTORE', file 'IStore_Lobs' on file 1.
Processed 0 pages for database 'ISTORE', file 'IStore_Memory_Optimized' on file 1.
Processed 0 pages for database 'ISTORE', file 'IStore_Logs_1' on file 1.
Processed 2 pages for database 'ISTORE', file 'IStore_Logs_2' on file 1.
BACKUP DATABASE successfully processed 1514 pages in 0.127 seconds (93.104 MB/sec).

#----------------------------------------------------------------------
# Stopping SQL Server container
#----------------------------------------------------------------------
sqlserver.config-demo_4.4.1

#----------------------------------------------------------------------
# Copying configs
#----------------------------------------------------------------------
cp: '/home/sdor/analyze-containers/licenses.conf' and '/home/sdor/analyze-containers/licenses.conf' are the same file

**Comment by Anthony-Johnson-i2** [comment]
Hi @Kirk-Fitzsimons-i2   just pinging you in case you did not see Steven's response.

**Comment by Anthony-Johnson-i2** [comment]
Hi 

I am sorry that it is taking so long for someone to get back to you regarding this.

I have spoken with Kirk and another member of the team a couple of times and have been assured that someone will look into this for you.

Cheers

**Comment by Kirk-Fitzsimons-i2** [comment]
Hi Steven,

A couple of things to note, you can not change the database dialect without redeploying.
Also it seems as if you are trying to run the upgrade from the 2.5.0 version of analyze-containers.

`vscode ➜ /home/sdor/analyze-containers $ manage-environment -t upgrade`

You must run the upgrade from the 2.5.2 version of analyze containers.

I am not sure about the issue you see with the tar.gz in the other ticket but could be related to this.

I would suggest you try the following:

1. Delete the analyze-containers-252 directory
2. Ensure that you have a working 2.5.0 deployment deployed
3. Restart the upgrade process from scratch (ensure that you run the upgrade from the 252 version of analyze-containers)

Kirk

**Comment by sdorresteijn88** [comment]
Hi Alex,

I started again finally with version 2.5.2. I think I ran the upgrade from old container, so that's probably the issue.
